require "fileutils"
require "digest"
require "shellwords"

HARNESS_ROOT  = __dir__
VENDOR_DIR    = File.join(HARNESS_ROOT, "vendor")
PICORUBY_SRC  = File.join(VENDOR_DIR, "picoruby")
PICORUBY_REPO = ENV["PICORUBY_REPO"] || "https://github.com/picoruby/picoruby.git"
PICORUBY_REF  = ENV["PICORUBY_REF"]  || "master"
BUILD_DIR     = File.join(HARNESS_ROOT, "build")

# ハーネスが持つ gem。build_config が gemdir: で指し、test:host がこの順で回す。
HARNESS_GEMS = %w[
  picoruby-usb-peripheral
  picoruby-usb-peripheral-cdc-midi
  picoruby-usb-peripheral-hid-mouse
].freeze

# upstream の r2p2 rake task は build_config の path を自分で決め打つので、
# ハーネスの build_config を渡す口が無い。vendor の中のこの1 file だけを
# 「ハーネスの build_config を load するだけ」の shim に置き換える。
OVERLAY_TARGET    = "build_config/r2p2-picoruby-pico2_w.rb".freeze
OVERLAY_PRESERVED = "build_config/r2p2-picoruby-pico2_w.upstream.rb".freeze
OVERLAY_MARKER    = "# generated by R2P2-dev-harness".freeze

# ホストで build するのに要る submodule だけ。pico-sdk は rp2040 の話なので入れない
# (`rake rp2040:setup` が別に取る)。
HOST_SUBMODULES = %w[
  mrbgems/picoruby-mruby/lib/mruby
  mrbgems/mruby-compiler
  mrbgems/mruby-bin-mrbc
  mrbgems/picoruby-machine/lib/estalloc
  mrbgems/picoruby-regexp_light/lib/regex_light
  mrbgems/picoruby-littlefs/lib/littlefs
].freeze

# upstream の pin から外して固定する submodule。`rake setup` / `refresh` が
# submodule を取ったあとにここへ checkout し直す。
#
# picoruby 4fe6e254 ("upgrade submodules") 以降の mruby-compiler は Prism の
# arena allocator を持ち、compiler context ごとに 64KB を mrb_malloc する
# (MRC_PRISM_ARENA_BLOCK、build_config からは変えられない)。heap 396KB の
# Pico 2 W では起動時の "Loading /etc/init.d/r2p2..." で止まり、CDC ごと固まる。
# 1つ前の pin では同じ board・同じ FS で shell まで上がる (docs/spec.md §6)。
# 外す条件: mruby 5a7aa02a1 が MRC_PRISM_ARENA_BLOCK を #ifndef で上書き可能にした
# (mruby-compiler2 では beb0107 から)。picoruby の mrbgems/mruby-compiler の pin が
# それを含んだら、この固定を外し、build_config/rp2040-pico2_w.rb で
# MRC_PRISM_ARENA_BLOCK=4096 を define する。3つは同期して動くので混ぜない。
SUBMODULE_PINS = {
  "mrbgems/picoruby-mruby/lib/mruby" => "b05a7bfda8ac192ab33f4f192d972c2794d2b170",
  "mrbgems/mruby-compiler"           => "db0aea5c1773c50244b6ee44f43170e45ad2253e",
  "mrbgems/mruby-bin-mrbc"           => "fa77fbde4ac20c00a2df2ddb2479e6ba2996f347"
}.freeze

def vendor_ready?
  File.directory?(File.join(PICORUBY_SRC, ".git"))
end

def require_vendor!
  return if vendor_ready?
  raise "vendor/picoruby is not there. Run `rake setup` first."
end

# vendor の中で rake を回す。
#
# `rake` が PATH に無い環境 (rbenv の shim が効いていない CI など) でも通るように
# ruby 経由で叩く。それだけでは足りない: upstream の r2p2 task は自分の中で
# `sh "... rake"` と裸の rake を呼ぶので、**子プロセスの PATH にも rake が要る**。
# rake の exe が居る dir を PATH の先頭に足して渡す。
def vendor_rake(env, *args)
  require_vendor!
  rake = begin
           Gem.bin_path("rake", "rake")
         rescue StandardError
           nil
         end
  command = rake ? "#{RbConfig.ruby.shellescape} #{rake.shellescape}" : "rake"
  child_env = env.dup
  if rake
    child_env["PATH"] = [File.dirname(rake), ENV["PATH"]].compact.join(File::PATH_SEPARATOR)
  end
  FileUtils.cd(PICORUBY_SRC) do
    sh child_env, "#{command} #{args.map(&:shellescape).join(' ')}"
  end
end

desc "Everything that can be checked without a board"
task test: ["test:host", "test:examples"]

task default: [:test]
