// generated by tools/fpga/gen_pkg.rb (rake fpga:gen). Do not edit.
// opcode 番号は mruby の include/mruby/ops.h、I/O は tools/fpga/io_map.rb。
`timescale 1ns / 1ps
// 定数はどれを使うかが module ごとに違うので、未使用の lint は切る
/* verilator lint_off UNUSEDPARAM */
package mrb_pkg;
  // レジスタの値 = {tag[TAG_BITS-1:0], value[31:0]}。OBJ はヒープの語アドレス、FWD / HDR はヒープの中だけ
  localparam int INT_BITS = 32;
  localparam int TAG_BITS = 4;
  localparam int VAL_BITS = INT_BITS + TAG_BITS;
  localparam logic [TAG_BITS-1:0] TAG_NIL   = 4'd0;
  localparam logic [TAG_BITS-1:0] TAG_FALSE = 4'd1;
  localparam logic [TAG_BITS-1:0] TAG_TRUE  = 4'd2;
  localparam logic [TAG_BITS-1:0] TAG_INT   = 4'd3;
  localparam logic [TAG_BITS-1:0] TAG_SYM   = 4'd4;
  localparam logic [TAG_BITS-1:0] TAG_CLASS = 4'd5;
  localparam logic [TAG_BITS-1:0] TAG_OBJ   = 4'd6;
  localparam logic [TAG_BITS-1:0] TAG_FWD   = 4'd7;
  localparam logic [TAG_BITS-1:0] TAG_HDR   = 4'd8;

  // ヒープ (tools/fpga/isa.rb)。見出しの値 = クラス << 16 | 中身の語数
  localparam int HEAP_SIZE = 2048;
  localparam logic [15:0] CLS_OBJECT = 16'd1;
  localparam logic [15:0] CLS_NIL    = 16'd2;
  localparam logic [15:0] CLS_TRUE   = 16'd3;
  localparam logic [15:0] CLS_FALSE  = 16'd4;
  localparam logic [15:0] CLS_INT    = 16'd5;
  localparam logic [15:0] CLS_SYM    = 16'd6;
  localparam logic [15:0] CLS_ARRAY  = 16'd7;
  localparam logic [15:0] CLS_PROC   = 16'd8;
  localparam logic [15:0] CLS_CLASS  = 16'd9;
  localparam logic [15:0] CLS_DATA   = 16'd32752;
  localparam logic [15:0] CLS_ENV    = 16'd32753;
  localparam logic [15:0] CLS_META   = 16'h8000;
  localparam logic [15:0] FIRST_USER_CLASS = 16'd32;

  // コアの大きさ (tools/fpga/isa.rb)
  localparam int RF_SIZE     = 128;
  localparam int STACK_DEPTH = 16;
  localparam int NCONST      = 64;

  // メソッド表 (tools/fpga/isa.rb)。1語 = {クラス, シンボル, 飛び先}。飛び先の上位 2bit が種類
  localparam logic [15:0] SUPER_SYM = 16'hffff;
  localparam int MAX_SUPER_DEPTH = 32;
  localparam logic [1:0] TGT_PC = 2'd0;
  localparam logic [1:0] TGT_PRIM = 2'd1;
  localparam logic [1:0] TGT_IVAR = 2'd2;
  localparam logic [1:0] TGT_IVSET = 2'd3;
  localparam logic [15:0] NIVARS_SYM = 16'hfffe;
  localparam logic [15:0] ISA_BIT = 16'h4000;
  // 演算の命令の落ち先のシンボルの番号 (OP_SYMS)
  localparam logic [15:0] SYM_ADD  = 16'd0; // +
  localparam logic [15:0] SYM_SUB  = 16'd1; // -
  localparam logic [15:0] SYM_MUL  = 16'd2; // *
  localparam logic [15:0] SYM_DIV  = 16'd3; // /
  localparam logic [15:0] SYM_EQ   = 16'd4; // ==
  localparam logic [15:0] SYM_LT   = 16'd5; // <
  localparam logic [15:0] SYM_LE   = 16'd6; // <=
  localparam logic [15:0] SYM_GT   = 16'd7; // >
  localparam logic [15:0] SYM_GE   = 16'd8; // >=
  localparam logic [15:0] SYM_AREF = 16'd9; // []
  localparam logic [15:0] SYM_ASET = 16'd10; // []=
  localparam logic [15:0] SYM_INIT = 16'd11; // initialize

  // primitive (tools/fpga/isa.rb の PRIMS)。メソッド表の飛び先の番号
  localparam logic [13:0] PR_IADD     = 14'd0; // Integer#+ (1 arg)
  localparam logic [13:0] PR_ISUB     = 14'd1; // Integer#- (1 arg)
  localparam logic [13:0] PR_IMUL     = 14'd2; // Integer#* (1 arg)
  localparam logic [13:0] PR_IDIV     = 14'd3; // Integer#/ (1 arg)
  localparam logic [13:0] PR_ILT      = 14'd4; // Integer#< (1 arg)
  localparam logic [13:0] PR_ILE      = 14'd5; // Integer#<= (1 arg)
  localparam logic [13:0] PR_IGT      = 14'd6; // Integer#> (1 arg)
  localparam logic [13:0] PR_IGE      = 14'd7; // Integer#>= (1 arg)
  localparam logic [13:0] PR_IEQ      = 14'd8; // Integer#== (1 arg)
  localparam logic [13:0] PR_MOD      = 14'd9; // Integer#% (1 arg)
  localparam logic [13:0] PR_NEG      = 14'd10; // Integer#-@ (0 arg)
  localparam logic [13:0] PR_SHL      = 14'd11; // Integer#<< (1 arg)
  localparam logic [13:0] PR_SHR      = 14'd12; // Integer#>> (1 arg)
  localparam logic [13:0] PR_AND      = 14'd13; // Integer#& (1 arg)
  localparam logic [13:0] PR_OR       = 14'd14; // Integer#| (1 arg)
  localparam logic [13:0] PR_XOR      = 14'd15; // Integer#^ (1 arg)
  localparam logic [13:0] PR_INV      = 14'd16; // Integer#~ (0 arg)
  localparam logic [13:0] PR_ABS      = 14'd17; // Integer#abs (0 arg)
  localparam logic [13:0] PR_ZERO     = 14'd18; // Integer#zero? (0 arg)
  localparam logic [13:0] PR_EVEN     = 14'd19; // Integer#even? (0 arg)
  localparam logic [13:0] PR_ODD      = 14'd20; // Integer#odd? (0 arg)
  localparam logic [13:0] PR_NOT      = 14'd21; // Object#! (0 arg)
  localparam logic [13:0] PR_OEQ      = 14'd22; // Object#== (1 arg)
  localparam logic [13:0] PR_CLASSOF  = 14'd23; // Object#class (0 arg)
  localparam logic [13:0] PR_SLEEPMS  = 14'd24; // Object#sleep_ms (1 arg)
  localparam logic [13:0] PR_SLEEP    = 14'd25; // Object#sleep (1 arg)
  localparam logic [13:0] PR_LAMBDA   = 14'd26; // Object#lambda (0 arg)
  localparam logic [13:0] PR_ISA      = 14'd27; // Object#is_a? (1 arg)
  localparam logic [13:0] PR_KINDOF   = 14'd28; // Object#kind_of? (1 arg)
  localparam logic [13:0] PR_RESPOND  = 14'd29; // Object#respond_to? (1 arg)
  localparam logic [13:0] PR_NEW      = 14'd30; // Class#new (any)
  localparam logic [13:0] PR_SIZE     = 14'd31; // Array#size (0 arg)
  localparam logic [13:0] PR_LENGTH   = 14'd32; // Array#length (0 arg)
  localparam logic [13:0] PR_EMPTY    = 14'd33; // Array#empty? (0 arg)
  localparam logic [13:0] PR_FIRST    = 14'd34; // Array#first (0 arg)
  localparam logic [13:0] PR_LAST     = 14'd35; // Array#last (0 arg)
  localparam logic [13:0] PR_POP      = 14'd36; // Array#pop (0 arg)
  localparam logic [13:0] PR_PUSH     = 14'd37; // Array#push (1 arg)
  localparam logic [13:0] PR_APUSH    = 14'd38; // Array#<< (1 arg)
  localparam logic [13:0] PR_AGET     = 14'd39; // Array#[] (1 arg)
  localparam logic [13:0] PR_ASET     = 14'd40; // Array#[]= (2 arg)
  localparam logic [13:0] PR_CALL     = 14'd41; // Proc#call (any)
  // 引数の数 (8'hff は何個でも)
  function automatic logic [7:0] prim_nargs(input logic [13:0] p);
    case (p)
      PR_IADD    : return 8'h01;
      PR_ISUB    : return 8'h01;
      PR_IMUL    : return 8'h01;
      PR_IDIV    : return 8'h01;
      PR_ILT     : return 8'h01;
      PR_ILE     : return 8'h01;
      PR_IGT     : return 8'h01;
      PR_IGE     : return 8'h01;
      PR_IEQ     : return 8'h01;
      PR_MOD     : return 8'h01;
      PR_NEG     : return 8'h00;
      PR_SHL     : return 8'h01;
      PR_SHR     : return 8'h01;
      PR_AND     : return 8'h01;
      PR_OR      : return 8'h01;
      PR_XOR     : return 8'h01;
      PR_INV     : return 8'h00;
      PR_ABS     : return 8'h00;
      PR_ZERO    : return 8'h00;
      PR_EVEN    : return 8'h00;
      PR_ODD     : return 8'h00;
      PR_NOT     : return 8'h00;
      PR_OEQ     : return 8'h01;
      PR_CLASSOF : return 8'h00;
      PR_SLEEPMS : return 8'h01;
      PR_SLEEP   : return 8'h01;
      PR_LAMBDA  : return 8'h00;
      PR_ISA     : return 8'h01;
      PR_KINDOF  : return 8'h01;
      PR_RESPOND : return 8'h01;
      PR_NEW     : return 8'hff;
      PR_SIZE    : return 8'h00;
      PR_LENGTH  : return 8'h00;
      PR_EMPTY   : return 8'h00;
      PR_FIRST   : return 8'h00;
      PR_LAST    : return 8'h00;
      PR_POP     : return 8'h00;
      PR_PUSH    : return 8'h01;
      PR_APUSH   : return 8'h01;
      PR_AGET    : return 8'h01;
      PR_ASET    : return 8'h02;
      PR_CALL    : return 8'hff;
      default: return 8'h00;
    endcase
  endfunction

  // I/O
  localparam int NPORTS = 4;
  localparam logic [NPORTS-1:0] IN_MASK = 4'b0100;
  localparam int PORT_LED = 0; // $LED (out)
  localparam int PORT_LED2 = 1; // $LED2 (out)
  localparam int PORT_BUTTON = 2; // $BUTTON (in)

  // 対応命令 (tools/fpga/isa.rb の SUPPORTED)
  localparam logic [7:0] OP_NOP        = 8'd0; // Z
  localparam logic [7:0] OP_MOVE       = 8'd1; // BB
  localparam logic [7:0] OP_LOADI8     = 8'd3; // BB
  localparam logic [7:0] OP_LOADINEG   = 8'd4; // BB
  localparam logic [7:0] OP_LOADI__1   = 8'd5; // B
  localparam logic [7:0] OP_LOADI_0    = 8'd6; // B
  localparam logic [7:0] OP_LOADI_1    = 8'd7; // B
  localparam logic [7:0] OP_LOADI_2    = 8'd8; // B
  localparam logic [7:0] OP_LOADI_3    = 8'd9; // B
  localparam logic [7:0] OP_LOADI_4    = 8'd10; // B
  localparam logic [7:0] OP_LOADI_5    = 8'd11; // B
  localparam logic [7:0] OP_LOADI_6    = 8'd12; // B
  localparam logic [7:0] OP_LOADI_7    = 8'd13; // B
  localparam logic [7:0] OP_LOADI16    = 8'd14; // BS
  localparam logic [7:0] OP_LOADI32    = 8'd15; // BSS
  localparam logic [7:0] OP_LOADSYM    = 8'd16; // BB
  localparam logic [7:0] OP_LOADNIL    = 8'd17; // B
  localparam logic [7:0] OP_LOADTRUE   = 8'd19; // B
  localparam logic [7:0] OP_LOADFALSE  = 8'd20; // B
  localparam logic [7:0] OP_GETGV      = 8'd21; // BB
  localparam logic [7:0] OP_SETGV      = 8'd22; // BB
  localparam logic [7:0] OP_GETIV      = 8'd25; // BB
  localparam logic [7:0] OP_SETIV      = 8'd26; // BB
  localparam logic [7:0] OP_GETCONST   = 8'd29; // BB
  localparam logic [7:0] OP_SETCONST   = 8'd30; // BB
  localparam logic [7:0] OP_GETUPVAR   = 8'd33; // BBB
  localparam logic [7:0] OP_SETUPVAR   = 8'd34; // BBB
  localparam logic [7:0] OP_GETIDX     = 8'd35; // B
  localparam logic [7:0] OP_GETIDX0    = 8'd36; // BB
  localparam logic [7:0] OP_SETIDX     = 8'd37; // B
  localparam logic [7:0] OP_JMP        = 8'd38; // S
  localparam logic [7:0] OP_JMPIF      = 8'd39; // BS
  localparam logic [7:0] OP_JMPNOT     = 8'd40; // BS
  localparam logic [7:0] OP_JMPNIL     = 8'd41; // BS
  localparam logic [7:0] OP_SSEND      = 8'd47; // BBB
  localparam logic [7:0] OP_SSEND0     = 8'd48; // BB
  localparam logic [7:0] OP_SEND       = 8'd50; // BBB
  localparam logic [7:0] OP_SEND0      = 8'd51; // BB
  localparam logic [7:0] OP_BLKCALL    = 8'd54; // BB
  localparam logic [7:0] OP_SUPER      = 8'd55; // BB
  localparam logic [7:0] OP_ARGARY     = 8'd56; // BS
  localparam logic [7:0] OP_ENTER      = 8'd57; // W
  localparam logic [7:0] OP_RETURN     = 8'd61; // B
  localparam logic [7:0] OP_RETURN_BLK = 8'd62; // B
  localparam logic [7:0] OP_RETNIL     = 8'd64; // Z
  localparam logic [7:0] OP_BREAK      = 8'd67; // B
  localparam logic [7:0] OP_BLKPUSH    = 8'd68; // BS
  localparam logic [7:0] OP_ADD        = 8'd69; // B
  localparam logic [7:0] OP_ADDI       = 8'd70; // BB
  localparam logic [7:0] OP_SUB        = 8'd71; // B
  localparam logic [7:0] OP_SUBI       = 8'd72; // BB
  localparam logic [7:0] OP_ADDILV     = 8'd73; // BBB
  localparam logic [7:0] OP_SUBILV     = 8'd74; // BBB
  localparam logic [7:0] OP_MUL        = 8'd75; // B
  localparam logic [7:0] OP_DIV        = 8'd76; // B
  localparam logic [7:0] OP_EQ         = 8'd77; // B
  localparam logic [7:0] OP_LT         = 8'd78; // B
  localparam logic [7:0] OP_LE         = 8'd79; // B
  localparam logic [7:0] OP_GT         = 8'd80; // B
  localparam logic [7:0] OP_GE         = 8'd81; // B
  localparam logic [7:0] OP_ARRAY      = 8'd82; // BB
  localparam logic [7:0] OP_ARRAY2     = 8'd83; // BBB
  localparam logic [7:0] OP_ARYCAT     = 8'd84; // B
  localparam logic [7:0] OP_ARYPUSH    = 8'd85; // BB
  localparam logic [7:0] OP_AREF       = 8'd87; // BBB
  localparam logic [7:0] OP_APOST      = 8'd89; // BBB
  localparam logic [7:0] OP_BLOCK      = 8'd98; // BB
  localparam logic [7:0] OP_CLASS      = 8'd103; // BB
  localparam logic [7:0] OP_EXEC       = 8'd105; // BB
  localparam logic [7:0] OP_TDEF       = 8'd107; // BBB
  localparam logic [7:0] OP_SDEF       = 8'd108; // BBB
  localparam logic [7:0] OP_STOP       = 8'd118; // Z
  localparam logic [7:0] OP_TABLE      = 8'd240; // BS
endpackage
