// generated by tools/fpga/gen_pkg.rb (rake fpga:gen). Do not edit.
// opcode 番号は mruby の include/mruby/ops.h、I/O は tools/fpga/io_map.rb。
`timescale 1ns / 1ps
// 定数はどれを使うかが module ごとに違うので、未使用の lint は切る
/* verilator lint_off UNUSEDPARAM */
package mrb_pkg;
  // レジスタの値 = {tag[1:0], value[31:0]}
  localparam int INT_BITS = 32;
  localparam int VAL_BITS = INT_BITS + 2;
  localparam logic [1:0] TAG_NIL   = 2'd0;
  localparam logic [1:0] TAG_FALSE = 2'd1;
  localparam logic [1:0] TAG_TRUE  = 2'd2;
  localparam logic [1:0] TAG_INT   = 2'd3;

  // I/O
  localparam int NPORTS = 4;
  localparam logic [NPORTS-1:0] IN_MASK = 4'b0100;
  localparam int PORT_LED = 0; // $LED (out)
  localparam int PORT_LED2 = 1; // $LED2 (out)
  localparam int PORT_BUTTON = 2; // $BUTTON (in)

  // 対応命令 (tools/fpga/isa.rb の SUPPORTED)
  localparam logic [7:0] OP_NOP       = 8'd0; // Z
  localparam logic [7:0] OP_MOVE      = 8'd1; // BB
  localparam logic [7:0] OP_LOADI8    = 8'd3; // BB
  localparam logic [7:0] OP_LOADINEG  = 8'd4; // BB
  localparam logic [7:0] OP_LOADI__1  = 8'd5; // B
  localparam logic [7:0] OP_LOADI_0   = 8'd6; // B
  localparam logic [7:0] OP_LOADI_1   = 8'd7; // B
  localparam logic [7:0] OP_LOADI_2   = 8'd8; // B
  localparam logic [7:0] OP_LOADI_3   = 8'd9; // B
  localparam logic [7:0] OP_LOADI_4   = 8'd10; // B
  localparam logic [7:0] OP_LOADI_5   = 8'd11; // B
  localparam logic [7:0] OP_LOADI_6   = 8'd12; // B
  localparam logic [7:0] OP_LOADI_7   = 8'd13; // B
  localparam logic [7:0] OP_LOADI16   = 8'd14; // BS
  localparam logic [7:0] OP_LOADI32   = 8'd15; // BSS
  localparam logic [7:0] OP_LOADNIL   = 8'd17; // B
  localparam logic [7:0] OP_LOADTRUE  = 8'd19; // B
  localparam logic [7:0] OP_LOADFALSE = 8'd20; // B
  localparam logic [7:0] OP_GETGV     = 8'd21; // BB
  localparam logic [7:0] OP_SETGV     = 8'd22; // BB
  localparam logic [7:0] OP_JMP       = 8'd38; // S
  localparam logic [7:0] OP_JMPIF     = 8'd39; // BS
  localparam logic [7:0] OP_JMPNOT    = 8'd40; // BS
  localparam logic [7:0] OP_JMPNIL    = 8'd41; // BS
  localparam logic [7:0] OP_RETURN    = 8'd61; // B
  localparam logic [7:0] OP_RETNIL    = 8'd64; // Z
  localparam logic [7:0] OP_ADD       = 8'd69; // B
  localparam logic [7:0] OP_ADDI      = 8'd70; // BB
  localparam logic [7:0] OP_SUB       = 8'd71; // B
  localparam logic [7:0] OP_SUBI      = 8'd72; // BB
  localparam logic [7:0] OP_ADDILV    = 8'd73; // BBB
  localparam logic [7:0] OP_SUBILV    = 8'd74; // BBB
  localparam logic [7:0] OP_EQ        = 8'd77; // B
  localparam logic [7:0] OP_LT        = 8'd78; // B
  localparam logic [7:0] OP_LE        = 8'd79; // B
  localparam logic [7:0] OP_GT        = 8'd80; // B
  localparam logic [7:0] OP_GE        = 8'd81; // B
  localparam logic [7:0] OP_STOP      = 8'd118; // Z
endpackage
