// generated by tools/fpga/gen_pkg.rb (rake fpga:gen). Do not edit.
// opcode 番号は mruby の include/mruby/ops.h、I/O は tools/fpga/io_map.rb。
`timescale 1ns / 1ps
// 定数はどれを使うかが module ごとに違うので、未使用の lint は切る
/* verilator lint_off UNUSEDPARAM */
package mrb_pkg;
  // レジスタの値 = {tag[TAG_BITS-1:0], value[31:0]}。ARRAY / PROC はヒープの語アドレス、FWD / HDR はヒープの中だけ
  localparam int INT_BITS = 32;
  localparam int TAG_BITS = 3;
  localparam int VAL_BITS = INT_BITS + TAG_BITS;
  localparam logic [TAG_BITS-1:0] TAG_NIL   = 3'd0;
  localparam logic [TAG_BITS-1:0] TAG_FALSE = 3'd1;
  localparam logic [TAG_BITS-1:0] TAG_TRUE  = 3'd2;
  localparam logic [TAG_BITS-1:0] TAG_INT   = 3'd3;
  localparam logic [TAG_BITS-1:0] TAG_ARRAY = 3'd4;
  localparam logic [TAG_BITS-1:0] TAG_PROC  = 3'd5;
  localparam logic [TAG_BITS-1:0] TAG_FWD   = 3'd6;
  localparam logic [TAG_BITS-1:0] TAG_HDR   = 3'd7;

  // ヒープ (tools/fpga/isa.rb)。見出しの値 = 種類 << 16 | 中身の語数
  localparam int HEAP_SIZE = 2048;
  localparam int KIND_ARY = 1;
  localparam int KIND_DATA = 2;
  localparam int KIND_PROC = 3;

  // コアの大きさ (tools/fpga/isa.rb)
  localparam int RF_SIZE     = 128;
  localparam int STACK_DEPTH = 16;
  localparam int NCONST      = 16;

  // SEND / SEND0 の組み込みメソッド (tools/fpga/isa.rb の BUILTINS)。ROM の b に入る番号
  localparam int NBUILTIN = 24;
  localparam logic [7:0] BI_MOD    = 8'd0; // % (1 arg)
  localparam logic [7:0] BI_NEQ    = 8'd1; // != (1 arg)
  localparam logic [7:0] BI_NEG    = 8'd2; // -@ (0 arg)
  localparam logic [7:0] BI_SHL    = 8'd3; // << (1 arg)
  localparam logic [7:0] BI_SHR    = 8'd4; // >> (1 arg)
  localparam logic [7:0] BI_AND    = 8'd5; // & (1 arg)
  localparam logic [7:0] BI_OR     = 8'd6; // | (1 arg)
  localparam logic [7:0] BI_XOR    = 8'd7; // ^ (1 arg)
  localparam logic [7:0] BI_INV    = 8'd8; // ~ (0 arg)
  localparam logic [7:0] BI_NOT    = 8'd9; // ! (0 arg)
  localparam logic [7:0] BI_ABS    = 8'd10; // abs (0 arg)
  localparam logic [7:0] BI_ZERO   = 8'd11; // zero? (0 arg)
  localparam logic [7:0] BI_EVEN   = 8'd12; // even? (0 arg)
  localparam logic [7:0] BI_ODD    = 8'd13; // odd? (0 arg)
  localparam logic [7:0] BI_SIZE   = 8'd14; // size (0 arg)
  localparam logic [7:0] BI_LENGTH = 8'd15; // length (0 arg)
  localparam logic [7:0] BI_EMPTY  = 8'd16; // empty? (0 arg)
  localparam logic [7:0] BI_FIRST  = 8'd17; // first (0 arg)
  localparam logic [7:0] BI_LAST   = 8'd18; // last (0 arg)
  localparam logic [7:0] BI_POP    = 8'd19; // pop (0 arg)
  localparam logic [7:0] BI_PUSH   = 8'd20; // push (1 arg)
  localparam logic [7:0] BI_INCL   = 8'd21; // include? (1 arg)
  localparam logic [7:0] BI_SLEEPMS = 8'd22; // sleep_ms (1 arg)
  localparam logic [7:0] BI_SLEEP  = 8'd23; // sleep (1 arg)
  localparam logic [NBUILTIN-1:0] BI_ARGC1 = 24'b111100000000000011111011;

  // I/O
  localparam int NPORTS = 4;
  localparam logic [NPORTS-1:0] IN_MASK = 4'b0100;
  localparam int PORT_LED = 0; // $LED (out)
  localparam int PORT_LED2 = 1; // $LED2 (out)
  localparam int PORT_BUTTON = 2; // $BUTTON (in)

  // 対応命令 (tools/fpga/isa.rb の SUPPORTED)
  localparam logic [7:0] OP_NOP        = 8'd0; // Z
  localparam logic [7:0] OP_MOVE       = 8'd1; // BB
  localparam logic [7:0] OP_LOADI8     = 8'd3; // BB
  localparam logic [7:0] OP_LOADINEG   = 8'd4; // BB
  localparam logic [7:0] OP_LOADI__1   = 8'd5; // B
  localparam logic [7:0] OP_LOADI_0    = 8'd6; // B
  localparam logic [7:0] OP_LOADI_1    = 8'd7; // B
  localparam logic [7:0] OP_LOADI_2    = 8'd8; // B
  localparam logic [7:0] OP_LOADI_3    = 8'd9; // B
  localparam logic [7:0] OP_LOADI_4    = 8'd10; // B
  localparam logic [7:0] OP_LOADI_5    = 8'd11; // B
  localparam logic [7:0] OP_LOADI_6    = 8'd12; // B
  localparam logic [7:0] OP_LOADI_7    = 8'd13; // B
  localparam logic [7:0] OP_LOADI16    = 8'd14; // BS
  localparam logic [7:0] OP_LOADI32    = 8'd15; // BSS
  localparam logic [7:0] OP_LOADNIL    = 8'd17; // B
  localparam logic [7:0] OP_LOADTRUE   = 8'd19; // B
  localparam logic [7:0] OP_LOADFALSE  = 8'd20; // B
  localparam logic [7:0] OP_GETGV      = 8'd21; // BB
  localparam logic [7:0] OP_SETGV      = 8'd22; // BB
  localparam logic [7:0] OP_GETCONST   = 8'd29; // BB
  localparam logic [7:0] OP_SETCONST   = 8'd30; // BB
  localparam logic [7:0] OP_GETUPVAR   = 8'd33; // BBB
  localparam logic [7:0] OP_SETUPVAR   = 8'd34; // BBB
  localparam logic [7:0] OP_GETIDX     = 8'd35; // B
  localparam logic [7:0] OP_GETIDX0    = 8'd36; // BB
  localparam logic [7:0] OP_SETIDX     = 8'd37; // B
  localparam logic [7:0] OP_JMP        = 8'd38; // S
  localparam logic [7:0] OP_JMPIF      = 8'd39; // BS
  localparam logic [7:0] OP_JMPNOT     = 8'd40; // BS
  localparam logic [7:0] OP_JMPNIL     = 8'd41; // BS
  localparam logic [7:0] OP_SSEND      = 8'd47; // BBB
  localparam logic [7:0] OP_SSEND0     = 8'd48; // BB
  localparam logic [7:0] OP_SEND       = 8'd50; // BBB
  localparam logic [7:0] OP_SEND0      = 8'd51; // BB
  localparam logic [7:0] OP_BLKCALL    = 8'd54; // BB
  localparam logic [7:0] OP_ENTER      = 8'd57; // W
  localparam logic [7:0] OP_RETURN     = 8'd61; // B
  localparam logic [7:0] OP_RETURN_BLK = 8'd62; // B
  localparam logic [7:0] OP_RETNIL     = 8'd64; // Z
  localparam logic [7:0] OP_BREAK      = 8'd67; // B
  localparam logic [7:0] OP_BLKPUSH    = 8'd68; // BS
  localparam logic [7:0] OP_ADD        = 8'd69; // B
  localparam logic [7:0] OP_ADDI       = 8'd70; // BB
  localparam logic [7:0] OP_SUB        = 8'd71; // B
  localparam logic [7:0] OP_SUBI       = 8'd72; // BB
  localparam logic [7:0] OP_ADDILV     = 8'd73; // BBB
  localparam logic [7:0] OP_SUBILV     = 8'd74; // BBB
  localparam logic [7:0] OP_MUL        = 8'd75; // B
  localparam logic [7:0] OP_DIV        = 8'd76; // B
  localparam logic [7:0] OP_EQ         = 8'd77; // B
  localparam logic [7:0] OP_LT         = 8'd78; // B
  localparam logic [7:0] OP_LE         = 8'd79; // B
  localparam logic [7:0] OP_GT         = 8'd80; // B
  localparam logic [7:0] OP_GE         = 8'd81; // B
  localparam logic [7:0] OP_ARRAY      = 8'd82; // BB
  localparam logic [7:0] OP_ARRAY2     = 8'd83; // BBB
  localparam logic [7:0] OP_BLOCK      = 8'd98; // BB
  localparam logic [7:0] OP_TDEF       = 8'd107; // BBB
  localparam logic [7:0] OP_STOP       = 8'd118; // Z
endpackage
