# fpga/rtl/mrb_pkg.sv を isa.rb と io_map.rb から作る。
# `rake fpga:gen` が書き、`rake test:fpga` (gen_pkg_test.rb) が commit 済みのものと一致するかを見る。
require_relative "converter"

module FpgaGenPkg
  PATH = File.expand_path("../../fpga/rtl/mrb_pkg.sv", __dir__)

  module_function

  def render
    ops = FpgaIsa::SUPPORTED.map { |n| FpgaIsa.op(n) }.sort_by(&:num)
    width = ops.map { |o| o.name.size }.max
    lines = []
    lines << "// generated by tools/fpga/gen_pkg.rb (rake fpga:gen). Do not edit."
    lines << "// opcode 番号は mruby の include/mruby/ops.h、I/O は tools/fpga/io_map.rb。"
    lines << "`timescale 1ns / 1ps"
    lines << "// 定数はどれを使うかが module ごとに違うので、未使用の lint は切る"
    lines << "/* verilator lint_off UNUSEDPARAM */"
    lines << "package mrb_pkg;"
    lines << "  // レジスタの値 = {tag[1:0], value[31:0]}"
    lines << "  localparam int INT_BITS = #{FpgaIsa::INT_BITS};"
    lines << "  localparam int VAL_BITS = INT_BITS + 2;"
    lines << "  localparam logic [1:0] TAG_NIL   = 2'd#{FpgaIsa::TAG_NIL};"
    lines << "  localparam logic [1:0] TAG_FALSE = 2'd#{FpgaIsa::TAG_FALSE};"
    lines << "  localparam logic [1:0] TAG_TRUE  = 2'd#{FpgaIsa::TAG_TRUE};"
    lines << "  localparam logic [1:0] TAG_INT   = 2'd#{FpgaIsa::TAG_INT};"
    lines << ""
    lines << "  // I/O"
    lines << "  localparam int NPORTS = #{FpgaIoMap::NPORTS};"
    lines << "  localparam logic [NPORTS-1:0] IN_MASK = #{FpgaIoMap::NPORTS}'b#{FpgaIoMap::IN_MASK.to_s(2).rjust(FpgaIoMap::NPORTS, '0')};"
    FpgaIoMap::PORTS.each do |p|
      lines << "  localparam int PORT_#{p.name.delete('$')} = #{p.num}; // #{p.name} (#{p.dir})"
    end
    lines << ""
    lines << "  // 対応命令 (tools/fpga/isa.rb の SUPPORTED)"
    ops.each do |o|
      lines << format("  localparam logic [7:0] OP_%-#{width}s = 8'd%d; // %s", o.name, o.num, o.fmt)
    end
    lines << "endpackage"
    lines.join("\n") + "\n"
  end

  def write
    File.write(PATH, render)
  end

  def current?
    File.file?(PATH) && File.read(PATH) == render
  end
end
