# fpga/rtl/mrb_pkg.sv を isa.rb と io_map.rb から作る。
# `rake fpga:gen` が書き、`rake test:fpga` (gen_pkg_test.rb) が commit 済みのものと一致するかを見る。
require_relative "converter"

module FpgaGenPkg
  PATH = File.expand_path("../../fpga/rtl/mrb_pkg.sv", __dir__)

  module_function

  def render
    ops = FpgaIsa::SUPPORTED.map { |n| FpgaIsa.op(n) }.sort_by(&:num)
    width = ops.map { |o| o.name.size }.max
    lines = []
    lines << "// generated by tools/fpga/gen_pkg.rb (rake fpga:gen). Do not edit."
    lines << "// opcode 番号は mruby の include/mruby/ops.h、I/O は tools/fpga/io_map.rb。"
    lines << "`timescale 1ns / 1ps"
    lines << "// 定数はどれを使うかが module ごとに違うので、未使用の lint は切る"
    lines << "/* verilator lint_off UNUSEDPARAM */"
    lines << "package mrb_pkg;"
    lines << "  // レジスタの値 = {tag[TAG_BITS-1:0], value[31:0]}。ARRAY / PROC はヒープの語アドレス、FWD / HDR はヒープの中だけ"
    lines << "  localparam int INT_BITS = #{FpgaIsa::INT_BITS};"
    lines << "  localparam int TAG_BITS = #{FpgaIsa::TAG_BITS};"
    lines << "  localparam int VAL_BITS = INT_BITS + TAG_BITS;"
    %w[NIL FALSE TRUE INT ARRAY PROC FWD HDR].each do |t|
      lines << format("  localparam logic [TAG_BITS-1:0] TAG_%-5s = 3'd%d;", t, FpgaIsa.const_get("TAG_#{t}"))
    end
    lines << ""
    lines << "  // ヒープ (tools/fpga/isa.rb)。見出しの値 = 種類 << 16 | 中身の語数"
    lines << "  localparam int HEAP_SIZE = #{FpgaIsa::HEAP_SIZE};"
    %w[ARY DATA PROC].each { |k| lines << "  localparam int KIND_#{k} = #{FpgaIsa.const_get("KIND_#{k}")};" }
    lines << ""
    lines << "  // コアの大きさ (tools/fpga/isa.rb)"
    lines << "  localparam int RF_SIZE     = #{FpgaIsa::RF_SIZE};"
    lines << "  localparam int STACK_DEPTH = #{FpgaIsa::STACK_DEPTH};"
    lines << "  localparam int NCONST      = #{FpgaIsa::NCONST};"
    lines << ""
    lines << "  // SEND / SEND0 の組み込みメソッド (tools/fpga/isa.rb の BUILTINS)。ROM の b に入る番号"
    lines << "  localparam int NBUILTIN = #{FpgaIsa::BUILTINS.size};"
    FpgaIsa::BUILTINS.each_with_index do |(n, k), i|
      lines << format("  localparam logic [7:0] BI_%-6s = 8'd%d; // %s (%d arg)", builtin_const(n), i, n, k)
    end
    lines << "  localparam logic [NBUILTIN-1:0] BI_ARGC1 = #{FpgaIsa::BUILTINS.size}'b#{FpgaIsa::BUILTINS.reverse.map { |_, k| k }.join};"
    lines << ""
    lines << "  // I/O"
    lines << "  localparam int NPORTS = #{FpgaIoMap::NPORTS};"
    lines << "  localparam logic [NPORTS-1:0] IN_MASK = #{FpgaIoMap::NPORTS}'b#{FpgaIoMap::IN_MASK.to_s(2).rjust(FpgaIoMap::NPORTS, '0')};"
    FpgaIoMap::PORTS.each do |p|
      lines << "  localparam int PORT_#{p.name.delete('$')} = #{p.num}; // #{p.name} (#{p.dir})"
    end
    lines << ""
    lines << "  // 対応命令 (tools/fpga/isa.rb の SUPPORTED)"
    ops.each do |o|
      lines << format("  localparam logic [7:0] OP_%-#{width}s = 8'd%d; // %s", o.name, o.num, o.fmt)
    end
    lines << "endpackage"
    lines.join("\n") + "\n"
  end

  # 組み込みメソッドの名前を SystemVerilog の識別子にする
  BUILTIN_NAMES = {
    "%" => "MOD", "!=" => "NEQ", "-@" => "NEG", "<<" => "SHL", ">>" => "SHR", "&" => "AND", "|" => "OR",
    "^" => "XOR", "~" => "INV", "!" => "NOT", "abs" => "ABS", "zero?" => "ZERO", "even?" => "EVEN", "odd?" => "ODD",
    "size" => "SIZE", "length" => "LENGTH", "empty?" => "EMPTY", "first" => "FIRST", "last" => "LAST", "pop" => "POP",
    "push" => "PUSH", "include?" => "INCL", "sleep_ms" => "SLEEPMS", "sleep" => "SLEEP"
  }.freeze

  def builtin_const(name)
    BUILTIN_NAMES.fetch(name)
  end

  def write
    File.write(PATH, render)
  end

  def current?
    File.file?(PATH) && File.read(PATH) == render
  end
end
