# fpga/rtl/mrb_pkg.sv を isa.rb と io_map.rb から作る。
# `rake fpga:gen` が書き、`rake test:fpga` (gen_pkg_test.rb) が commit 済みのものと一致するかを見る。
require_relative "converter"

module FpgaGenPkg
  PATH = File.expand_path("../../fpga/rtl/mrb_pkg.sv", __dir__)

  module_function

  def render
    ops = FpgaIsa::SUPPORTED.map { |n| FpgaIsa.op(n) }.sort_by(&:num)
    width = ops.map { |o| o.name.size }.max
    lines = []
    lines << "// generated by tools/fpga/gen_pkg.rb (rake fpga:gen). Do not edit."
    lines << "// opcode 番号は mruby の include/mruby/ops.h、I/O は tools/fpga/io_map.rb。"
    lines << "`timescale 1ns / 1ps"
    lines << "// 定数はどれを使うかが module ごとに違うので、未使用の lint は切る"
    lines << "/* verilator lint_off UNUSEDPARAM */"
    lines << "package mrb_pkg;"
    lines << "  // レジスタの値 = {tag[TAG_BITS-1:0], value[31:0]}。OBJ はヒープの語アドレス、FWD / HDR はヒープの中だけ"
    lines << "  localparam int INT_BITS = #{FpgaIsa::INT_BITS};"
    lines << "  localparam int TAG_BITS = #{FpgaIsa::TAG_BITS};"
    lines << "  localparam int VAL_BITS = INT_BITS + TAG_BITS;"
    FpgaIsa::TAGS.each do |t|
      lines << format("  localparam logic [TAG_BITS-1:0] TAG_%-5s = %d'd%d;", t, FpgaIsa::TAG_BITS, FpgaIsa.const_get("TAG_#{t}"))
    end
    lines << ""
    lines << "  // ヒープ (tools/fpga/isa.rb)。見出しの値 = クラス << 16 | 中身の語数"
    lines << "  localparam int HEAP_SIZE = #{FpgaIsa::HEAP_SIZE};"
    %w[OBJECT NIL TRUE FALSE INT SYM ARRAY PROC CLASS STRING HASH RANGE FLOAT EXC DATA ENV BRK].each do |k|
      lines << format("  localparam logic [15:0] CLS_%-6s = 16'd%d;", k, FpgaIsa.const_get("CLS_#{k}"))
    end
    lines << "  localparam logic [15:0] CLS_META   = 16'h#{FpgaIsa::META.to_s(16)};"
    lines << "  localparam logic [15:0] FIRST_USER_CLASS = 16'd#{FpgaIsa::FIRST_USER_CLASS};"
    lines << ""
    lines << "  // コアの大きさ (tools/fpga/isa.rb)"
    lines << "  localparam int RF_SIZE     = #{FpgaIsa::RF_SIZE};"
    lines << "  localparam int STACK_DEPTH = #{FpgaIsa::STACK_DEPTH};"
    lines << "  localparam int NCONST      = #{FpgaIsa::NCONST};"
    lines << ""
    lines << "  // メソッド表 (tools/fpga/isa.rb)。1語 = {クラス, シンボル, 飛び先}。飛び先の上位 2bit が種類"
    lines << "  localparam logic [15:0] SUPER_SYM = 16'h#{FpgaIsa::SUPER_SYM.to_s(16)};"
    lines << "  localparam int MAX_SUPER_DEPTH = #{FpgaIsa::MAX_SUPER_DEPTH};"
    lines << "  localparam logic [1:0] TGT_PC = 2'd#{FpgaIsa::TGT_PC};"
    lines << "  localparam logic [1:0] TGT_PRIM = 2'd#{FpgaIsa::TGT_PRIM};"
    lines << "  localparam logic [1:0] TGT_IVAR = 2'd#{FpgaIsa::TGT_IVAR};"
    lines << "  localparam logic [1:0] TGT_IVSET = 2'd#{FpgaIsa::TGT_IVSET};"
    lines << "  localparam logic [15:0] NIVARS_SYM = 16'h#{FpgaIsa::NIVARS_SYM.to_s(16)};"
    lines << "  localparam logic [15:0] ISA_BIT = 16'h#{FpgaIsa::ISA_BIT.to_s(16)};"
    lines << "  localparam logic [15:0] NAME_SYM = 16'h#{FpgaIsa::NAME_SYM.to_s(16)};"
    lines << "  // 巻き戻しの塊の種類と、例外の表の種類 (tools/fpga/isa.rb)"
    %w[JUMP RET BRK BRK0].each { |k| lines << format("  localparam logic [2:0] BRK_%-4s = 3'd%d;", k, FpgaIsa.const_get("BRK_#{k}")) }
    lines << "  localparam logic CATCH_ENSURE = 1'b#{FpgaIsa::CATCH_ENSURE};"
    lines << "  // 演算の命令の落ち先のシンボルの番号 (OP_SYMS)"
    FpgaIsa::OP_SYMS.each_with_index do |s, i|
      lines << format("  localparam logic [15:0] SYM_%-4s = 16'd%d; // %s", OP_SYM_NAMES.fetch(s), i, s)
    end
    lines << ""
    lines << "  // primitive (tools/fpga/isa.rb の PRIMS)。メソッド表の飛び先の番号"
    FpgaIsa::PRIMS.each_with_index do |(cls, n, k, const), i|
      lines << format("  localparam logic [13:0] PR_%-8s = 14'd%d; // %s#%s (%s)", const, i, cls, n, k < 0 ? "any" : "#{k} arg")
    end
    lines << "  localparam int NPRIMS = #{FpgaIsa::PRIMS.size};"
    lines << "  // コアの実行時エラーの種類 (Integer#__core_error の受け手)"
    %w[ZERODIV NOMETHOD ARGNUM TYPE COMPARE FLOATDOMAIN RANGE].each { |k| lines << format("  localparam logic [2:0] CERR_%-11s = 3'd%d;", k, FpgaIsa.const_get("CERR_#{k}")) }
    lines << "  // 引数の数 (8'hff は何個でも)"
    lines << "  function automatic logic [7:0] prim_nargs(input logic [13:0] p);"
    lines << "    case (p)"
    FpgaIsa::PRIMS.each do |(_, _, k, const)|
      lines << format("      PR_%-8s: return 8'h%02x;", const, k & 0xFF)
    end
    lines << "      default: return 8'h00;"
    lines << "    endcase"
    lines << "  endfunction"
    lines << ""
    lines << "  // I/O"
    lines << "  localparam int NPORTS = #{FpgaIoMap::NPORTS};"
    lines << "  localparam logic [NPORTS-1:0] IN_MASK = #{FpgaIoMap::NPORTS}'b#{FpgaIoMap::IN_MASK.to_s(2).rjust(FpgaIoMap::NPORTS, '0')};"
    FpgaIoMap::PORTS.each do |p|
      lines << "  localparam int PORT_#{p.name.delete('$')} = #{p.num}; // #{p.name} (#{p.dir})"
    end
    lines << ""
    lines << "  // 対応命令 (tools/fpga/isa.rb の SUPPORTED)"
    ops.each do |o|
      lines << format("  localparam logic [7:0] OP_%-#{width}s = 8'd%d; // %s", o.name, o.num, o.fmt)
    end
    lines << "endpackage"
    lines.join("\n") + "\n"
  end

  # 演算の落ち先のシンボルの名前を SystemVerilog の識別子にする
  OP_SYM_NAMES = {
    "+" => "ADD", "-" => "SUB", "*" => "MUL", "/" => "DIV", "==" => "EQ", "<" => "LT", "<=" => "LE", ">" => "GT",
    ">=" => "GE", "[]" => "AREF", "[]=" => "ASET", "initialize" => "INIT", "__core_error" => "CERR"
  }.freeze

  def write
    File.write(PATH, render)
  end

  def current?
    File.file?(PATH) && File.read(PATH) == render
  end
end
