# PERIDOT-Air 向けの Quartus プロジェクトを組み、合成し、書き込む。
#
# Cyclone IV の bitstream は Intel Quartus でしか作れず、macOS 版は無い。合成は次のどちらかで回す:
#   - quartus_sh が PATH にある (x86 Linux / Windows 機でそのまま)
#   - FPGA_QUARTUS_HOST=<ssh 先> (Apple Silicon なら UTM の Linux VM)。rsync で送り、ssh で合成し、結果を戻す
# 書き込みは Mac ネイティブの openFPGALoader (USB-Blaster)。.sof は Quartus の quartus_cpf で .svf にしておく。
#
# プロジェクトは build/fpga/peridot_air/ に自己完結で作る (VM へそのまま送れるように、.sv は写す)。
require "fileutils"
require "shellwords"

module FpgaQuartus
  ROOT      = File.expand_path("../..", __dir__)
  BOARD_DIR = File.join(ROOT, "fpga", "boards", "peridot_air")
  RTL_DIR   = File.join(ROOT, "fpga", "rtl")
  PROJECT   = "mrb_peridot_air".freeze
  ROM_DEPTH = 1024 # mrb_soc の既定 PC_BITS = 10

  module_function

  # 合成に使う RTL。package を先に、テスト用の counter8 は入れない
  def sources
    Dir[File.join(RTL_DIR, "**", "*.sv")]
      .reject { |p| File.basename(p) == "counter8.sv" }
      .sort_by { |p| [p.end_with?("_pkg.sv") ? 0 : 1, p] }
  end

  # ROM の全語を埋めた $readmemh。空きは全 bit 1 (op 0xff、コアはエラーで止まる)。
  # hex は PicoRuby の変換器 (mrb2rom.rb) が書いたもの
  def rom_hex(hex, depth: ROM_DEPTH)
    lines = File.readlines(hex, chomp: true).map(&:strip).reject(&:empty?)
    raise ArgumentError, "program has #{lines.size} words, the ROM holds #{depth}" if lines.size > depth
    lines += ["f" * 12] * (depth - lines.size)
    lines.join("\n") + "\n"
  end

  def qsf(source_names, ce_div:)
    base = File.read(File.join(BOARD_DIR, "peridot_air.qsf"))
    extra = source_names.map { |n| "set_global_assignment -name SYSTEMVERILOG_FILE src/#{n}" }
    extra << "set_parameter -name ROM_FILE \"rom.hex\""
    extra << "set_parameter -name CE_DIV #{Integer(ce_div)}"
    "#{base}\n# ---- generated by rake fpga:build\n#{extra.join("\n")}\n"
  end

  # build/fpga/peridot_air/ にプロジェクトを書く。返り値はその dir
  def write_project(dir, hex, ce_div:)
    FileUtils.rm_rf dir
    FileUtils.mkdir_p File.join(dir, "src")
    names = sources.map do |src|
      name = File.basename(src)
      FileUtils.cp src, File.join(dir, "src", name)
      name
    end
    FileUtils.cp File.join(BOARD_DIR, "peridot_air.sdc"), dir
    File.write(File.join(dir, "#{PROJECT}.qpf"), "PROJECT_REVISION = \"#{PROJECT}\"\n")
    File.write(File.join(dir, "#{PROJECT}.qsf"), qsf(names, ce_div: ce_div))
    File.write(File.join(dir, "rom.hex"), rom_hex(hex))
    lst = hex.sub(/\.hex\z/, ".lst")
    FileUtils.cp lst, File.join(dir, "rom.lst") if File.file?(lst)
    dir
  end

  # プロジェクト dir の中で走らせるコマンド。.sof を作り、書き込み用の .svf に変える
  def compile_script
    [
      "quartus_sh --flow compile #{PROJECT}",
      "quartus_cpf -c -q 10MHz -g 3.3 -n p output_files/#{PROJECT}.sof output_files/#{PROJECT}.svf"
    ].join(" && ")
  end

  def svf_path(dir)
    File.join(dir, "output_files", "#{PROJECT}.svf")
  end

  # fit.summary から LE とメモリの使用量を拾う
  def fit_summary(dir)
    path = File.join(dir, "output_files", "#{PROJECT}.fit.summary")
    return nil unless File.file?(path)
    File.readlines(path, chomp: true).grep(/Total logic elements|Total registers|Total memory bits|Total pins|Fitter Status|Quartus Prime Version/)
  end
end
