# Raspberry Pi Pico 2 W 向けのタスク。
#
# 本 repo の完了条件は実機まで通って green (docs/spec.md §5) なので、
# build 以外はまだ「無い」ことを明示的に言う。黙って通ったふりはしない。
namespace :rp2040 do
  BOARD = "pico2_w".freeze

  desc "Init the pico-sdk submodule (big; only needed for firmware builds)"
  task :setup do
    require_vendor!
    FileUtils.cd(PICORUBY_SRC) do
      sh "git submodule update --init --recursive mrbgems/picoruby-r2p2/lib/pico-sdk"
    end
  end

  desc "Build the R2P2 firmware for Pico 2 W with the harness gems (prod)"
  task :build do
    require_vendor!
    ensure_overlay!
    invalidate_stale_firmware_build
    vendor_rake({}, "r2p2:picoruby:#{BOARD}:prod")
    uf2 = latest_uf2
    raise "no .uf2 came out of the build" unless uf2
    File.write(firmware_stamp_path, firmware_stamp)
    puts "firmware: #{uf2}"
  end

  desc "Print the .uf2 the last build produced"
  task :firmware do
    uf2 = latest_uf2
    raise "no firmware built yet. Run `rake rp2040:build`." unless uf2
    puts uf2
  end

  desc "Say whether the last firmware build is still good for the current inputs"
  task :stamp do
    want = firmware_stamp
    have = File.file?(firmware_stamp_path) ? File.read(firmware_stamp_path).strip : nil
    puts "inputs: #{want}"
    puts "built : #{have || '(never built)'}"
    puts(have == want ? "up to date" : "stale — the next build wipes build/ and starts over")
  end

  desc "Flash the firmware onto a Pico 2 W in BOOTSEL mode (unverified)"
  task :flash do
    uf2 = latest_uf2
    raise "no firmware built yet. Run `rake rp2040:build`." unless uf2
    require_picotool!
    puts <<~ASK
      Put the board into BOOTSEL: unplug USB, hold BOOTSEL, plug in, release.
      (Until the firmware gains a way back into BOOTSEL, this is a human step.
       See docs/handoff-to-mac.md.)
    ASK
    # picotool は mount を待つ。/Volumes/RP2350 への cp は mount 完了前に走ると
    # Device not configured で落ちる。ボリュームは見えているのに、である。
    sh "picotool load -x #{uf2.shellescape}"
  end

  desc "Copy a local .rb onto the board over PicoModem (unverified)"
  task :upload, [:src, :dst] do |_t, args|
    src = args[:src] or raise "usage: rake rp2040:upload[<local .rb>,</home/name.rb>]"
    dst = args[:dst] || "/home/#{File.basename(src)}"
    device_tool "pmput.rb", src, dst
  end

  desc "Run an app on the board and capture its log (unverified)"
  task :run, [:app, :seconds] do |_t, args|
    app = args[:app] or raise "usage: rake rp2040:run[<local .rb>,<seconds>]"
    seconds = args[:seconds] || "20"
    remote = "/home/#{File.basename(app)}"
    device_tool "pmput.rb", app, remote
    device_tool "runapp.rb", remote, seconds
  end

  desc "Reboot the board (unverified)"
  task :reboot do
    # R2P2 shell は入力を Ruby として評価しないので、プロンプトに Machine.reboot と
    # 打っても何も起きない。script を置いて実行する。
    device_tool "pmput.rb", File.join(HARNESS_ROOT, "tools", "pico2w", "reboot_app.rb"), "/home/reboot.rb"
    # 実行中に CDC が落ちるので ENXIO が出る。正常。
    device_tool "rsh.rb", "/home/reboot.rb", "4"
  end

  desc "build -> flash -> run -> judge (not implemented yet)"
  task :verify do
    raise <<~MSG
      rake rp2040:verify is not implemented yet.

      build / flash / run は揃ったが、**判定が無い**。CDC-MIDI なら
      「Mac が MIDI デバイスとして列挙したか」「送った event を受け取れたか」
      「teardown のあとに stuck note が残っていないか」を Mac 側で見る必要がある
      (docs/spec.md §5)。その相手役はまだ書いていない。

      判定が無いまま verify が通ると、完了の線引きが消える。だから落とす。
    MSG
  end
end

# 実機を触る helper は tools/pico2w/ に居る。serialport gem と、
# USB 製品名からポートを引くための macOS の ioreg が要る。
# どれもまだ実機で検証していない (docs/handoff-to-mac.md)。
def device_tool(name, *args)
  script = File.join(HARNESS_ROOT, "tools", "pico2w", name)
  raise "#{script} is missing" unless File.file?(script)
  sh "#{RbConfig.ruby.shellescape} #{script.shellescape} #{args.map { |a| a.to_s.shellescape }.join(' ')}"
end

def require_picotool!
  return if system("which picotool > /dev/null 2>&1")
  raise <<~MSG
    picotool is not on PATH.

    The firmware exposes no mass storage and no reset interface, so picotool is
    the only way in. `cp` to /Volumes/RP2350 is not a substitute.
  MSG
end

def firmware_build_dir
  File.join(PICORUBY_SRC, "build", "r2p2", "picoruby", "pico2_w", "prod")
end

def latest_uf2
  Dir[File.join(firmware_build_dir, "*.uf2")].max_by { |f| File.mtime(f) }
end

def ensure_overlay!
  shim = File.join(PICORUBY_SRC, "build_config", "r2p2-picoruby-pico2_w.rb")
  return if File.exist?(shim) && File.read(shim).start_with?("# generated by R2P2-dev-harness")
  Rake::Task["vendor:overlay"].invoke
end

# build/<name>/ の stale 化を止める。
#
# mruby の compile rule は .c の mtime しか見ないので、vendor/picoruby を
# 取得し直しても、build_config を変えても、既存の .o の方が新しければ何も
# 再 compile されない。build task は成功したと言いながら前の archive を stage する。
# 入力の digest を build dir に記録し、変わっていたら dir ごと捨てる。
def firmware_stamp
  sha = File.directory?(File.join(PICORUBY_SRC, ".git")) ? `git -C #{PICORUBY_SRC.shellescape} rev-parse HEAD`.strip : ""
  inputs = [sha]
  inputs << Digest::SHA256.file(File.join(HARNESS_ROOT, "build_config", "rp2040-pico2_w.rb")).hexdigest
  HARNESS_GEMS.each do |name|
    Dir[File.join(HARNESS_ROOT, "gems", name, "**", "*")].sort.each do |path|
      next unless File.file?(path)
      inputs << Digest::SHA256.file(path).hexdigest
    end
  end
  Digest::SHA256.hexdigest(inputs.join("\n"))
end

def firmware_stamp_path
  File.join(firmware_build_dir, ".harness-build-stamp")
end

def invalidate_stale_firmware_build
  want = firmware_stamp
  stamp = firmware_stamp_path
  lib_dirs = [
    File.join(PICORUBY_SRC, "build", "r2p2-picoruby-pico2_w"),
    firmware_build_dir
  ]
  return unless File.directory?(firmware_build_dir)
  return if File.file?(stamp) && File.read(stamp).strip == want

  puts "picoruby, build_config or a harness gem changed since the last build — rebuilding from scratch"
  lib_dirs.each { |dir| FileUtils.rm_rf dir }
end
