# Raspberry Pi Pico 2 W 向けのタスク。
#
# 本 repo の完了条件は実機まで通って green (docs/spec.md §5) なので、
# build 以外はまだ「無い」ことを明示的に言う。黙って通ったふりはしない。
namespace :rp2040 do
  BOARD = "pico2_w".freeze

  desc "Init the pico-sdk submodule (big; only needed for firmware builds)"
  task :setup do
    require_vendor!
    FileUtils.cd(PICORUBY_SRC) do
      sh "git submodule update --init --recursive mrbgems/picoruby-r2p2/lib/pico-sdk"
    end
  end

  desc "Build the R2P2 firmware for Pico 2 W with the harness gems (prod)"
  task :build do
    require_vendor!
    ensure_overlay!
    invalidate_stale_firmware_build
    vendor_rake({}, "r2p2:picoruby:#{BOARD}:prod")
    uf2 = latest_uf2
    raise "no .uf2 came out of the build" unless uf2
    File.write(firmware_stamp_path, firmware_stamp)
    puts "firmware: #{uf2}"
  end

  desc "Print the .uf2 the last build produced"
  task :firmware do
    uf2 = latest_uf2
    raise "no firmware built yet. Run `rake rp2040:build`." unless uf2
    puts uf2
  end

  desc "Flash the firmware onto a Pico 2 W (not implemented yet)"
  task :flash do
    raise <<~MSG
      rake rp2040:flash is not implemented yet.

      Flashing needs a board on a USB port and, until the firmware gains a way
      back into BOOTSEL, a human to hold the button. The approach is settled in
      the Mac-local session; see docs/handoff-to-mac.md.

      For now: `rake rp2040:build`, then `picotool load -x <uf2>` on the Mac.
      Do not `cp` to /Volumes/RP2350 — it fails before the mount completes.
    MSG
  end

  desc "Run an app on the board and capture the log (not implemented yet)"
  task :run, [:app] do |_t, _args|
    raise <<~MSG
      rake rp2040:run is not implemented yet.

      It needs the PicoModem helpers (pmput / rsh / runapp) out of
      bash0C7/picoruby-ble-verify, and those can only be ported with a board in
      hand. See docs/handoff-to-mac.md §2.
    MSG
  end

  desc "build -> flash -> run -> judge (not implemented yet)"
  task :verify do
    raise <<~MSG
      rake rp2040:verify is not implemented yet: it depends on rp2040:flash and
      rp2040:run. Until it exists, a change is not done — the host tests
      (`rake test:host`) are necessary, never sufficient. See docs/spec.md §5.
    MSG
  end
end

def firmware_build_dir
  File.join(PICORUBY_SRC, "build", "r2p2", "picoruby", "pico2_w", "prod")
end

def latest_uf2
  Dir[File.join(firmware_build_dir, "*.uf2")].max_by { |f| File.mtime(f) }
end

def ensure_overlay!
  shim = File.join(PICORUBY_SRC, "build_config", "r2p2-picoruby-pico2_w.rb")
  return if File.exist?(shim) && File.read(shim).start_with?("# generated by R2P2-dev-harness")
  Rake::Task["vendor:overlay"].invoke
end

# build/<name>/ の stale 化を止める。
#
# mruby の compile rule は .c の mtime しか見ないので、vendor/picoruby を
# 取得し直しても、build_config を変えても、既存の .o の方が新しければ何も
# 再 compile されない。build task は成功したと言いながら前の archive を stage する。
# 入力の digest を build dir に記録し、変わっていたら dir ごと捨てる。
def firmware_stamp
  sha = File.directory?(File.join(PICORUBY_SRC, ".git")) ? `git -C #{PICORUBY_SRC.shellescape} rev-parse HEAD`.strip : ""
  inputs = [sha]
  inputs << Digest::SHA256.file(File.join(HARNESS_ROOT, "build_config", "rp2040-pico2_w.rb")).hexdigest
  HARNESS_GEMS.each do |name|
    Dir[File.join(HARNESS_ROOT, "gems", name, "**", "*")].sort.each do |path|
      next unless File.file?(path)
      inputs << Digest::SHA256.file(path).hexdigest
    end
  end
  Digest::SHA256.hexdigest(inputs.join("\n"))
end

def firmware_stamp_path
  File.join(firmware_build_dir, ".harness-build-stamp")
end

def invalidate_stale_firmware_build
  want = firmware_stamp
  stamp = firmware_stamp_path
  lib_dirs = [
    File.join(PICORUBY_SRC, "build", "r2p2-picoruby-pico2_w"),
    firmware_build_dir
  ]
  return unless File.directory?(firmware_build_dir)
  return if File.file?(stamp) && File.read(stamp).strip == want

  puts "picoruby, build_config or a harness gem changed since the last build — rebuilding from scratch"
  lib_dirs.each { |dir| FileUtils.rm_rf dir }
end
