desc "Fetch picoruby into vendor/picoruby (env: PICORUBY_REPO / PICORUBY_REF)"
task :setup do
  if vendor_ready?
    puts "vendor/picoruby is already there. `rake refresh` to re-fetch."
  else
    FileUtils.mkdir_p VENDOR_DIR
    sh "git clone --depth 1 --branch #{PICORUBY_REF.shellescape} #{PICORUBY_REPO.shellescape} #{PICORUBY_SRC.shellescape}"
  end
  Rake::Task["vendor:submodules"].invoke
  Rake::Task["vendor:overlay"].invoke
end

desc "Re-fetch PICORUBY_REF into the existing vendor/picoruby"
task :refresh do
  require_vendor!
  FileUtils.cd(PICORUBY_SRC) do
    sh "git fetch --depth 1 origin #{PICORUBY_REF.shellescape}"
    sh "git checkout --detach FETCH_HEAD"
  end
  Rake::Task["vendor:submodules"].invoke
  Rake::Task["vendor:overlay"].invoke
end

desc "Remove every build output (vendor/picoruby stays)"
task :clean do
  FileUtils.rm_rf BUILD_DIR
  if vendor_ready?
    FileUtils.rm_rf File.join(PICORUBY_SRC, "build")
  end
end

namespace :vendor do
  desc "Init the submodules a host build needs (pico-sdk is rp2040:setup's job)"
  task :submodules do
    require_vendor!
    FileUtils.cd(PICORUBY_SRC) do
      sh "git submodule update --init --depth 1 #{HOST_SUBMODULES.map(&:shellescape).join(' ')}"
    end
  end

  # vendor/picoruby は生成物。upstream の file を置き換えるのはここだけで、
  # 何を置き換えたかは必ずこの task に書く。
  #
  # upstream の r2p2 rake task は build_config の path を
  # "build_config/r2p2-<vm>-<board>.rb" と自分で決め打つので、ハーネスの
  # build_config をそのまま渡す口が無い。よって
  #
  #   - upstream の原本を *.upstream.rb へ退避し (初回だけ)
  #   - その名前の file を「ハーネスの build_config を load するだけ」の shim にする
  #
  # 中身はハーネス側 (build_config/rp2040-pico2_w.rb) に残るので、upstream の
  # 内容を複製することにはならない。`rake refresh` で毎回張り直す。
  desc "Point vendor's build_config at the harness build_config (generated shim)"
  task :overlay do
    require_vendor!
    original = File.join(PICORUBY_SRC, "build_config", "r2p2-picoruby-pico2_w.rb")
    preserved = File.join(PICORUBY_SRC, "build_config", "r2p2-picoruby-pico2_w.upstream.rb")
    marker = "# generated by R2P2-dev-harness"

    unless File.exist?(original)
      puts "vendor/picoruby has no r2p2-picoruby-pico2_w.rb. Skipping the overlay."
      next
    end

    if File.read(original).start_with?(marker)
      puts "overlay is already in place"
      next
    end

    FileUtils.cp original, preserved
    File.write(original, <<~SHIM)
      #{marker}. Do not edit; `rake refresh` rewrites it.
      # The real content lives in the harness at build_config/rp2040-pico2_w.rb.
      # The upstream original was preserved next to this file as
      # r2p2-picoruby-pico2_w.upstream.rb.
      load "#{File.join(HARNESS_ROOT, 'build_config', 'rp2040-pico2_w.rb')}"
    SHIM
    puts "overlay written: #{original}"
  end
end
